services:
  # PostgrSQL Datenbank
  db:
    image: postgres:15
    container_name: db_server
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_DEFAULT}
    volumes:
      # Links Pfad auf dem Pi, rechts Pfad im Container
      - /mnt/data/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Live-Streaming (Dauerhaft laufend während der Sessions)
  f1_live_ingestor:
    build:
      context: .
      dockerfile: projects/f1_live_tracker/Dockerfile
    container_name: f1_live_tracker
    restart: on-failure
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME_FUT}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./projects/f1_live_tracker:/app

  # Historische F1-Daten
  f1_history_etl:
    build:
      context: .
      dockerfile: projects/f1_history/Dockerfile
    container_name: f1_history_loader
    restart: "no"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME_FUT}
    volumes:
      - ./projects/f1_history:/app

  # FUTWIZ Scraper
  fifa_scraper:
    build:
      context: .
      dockerfile: projects/fut_market_scraper/Dockerfile
    container_name: fifa_market_scraper
    restart: "no"
    depends_on:
      - db
    environment:
      # Hier sagst du dem Container, dass die DB im Docker-Netzwerk "db" heißt
      - DB_HOST=db  
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_FUT}  # Hier legst du fest, in welche DB dieser Scraper schreibt
      - PYTHONPATH=/app # Das ist der Zaubertrick!
    volumes:
      - .:/app # Wir mounten das KOMPLETTE Hauptverzeichnis nach /app
    working_dir: /app/projects/fut_market_scraper # Wir starten aber im Scraper-Ordner

volumes:
  postgres_data:
    driver: local